### ISSUE TITLE
GRPC server graceful shutdown

### ISSUE THREAD

**Issue by o-shevchenko** [grpc-ecosystem/grpc-spring#1110]
**The context**
We deploy our service in K8s and provide a gRPC streaming API so the server can hold open connections for a period of time.
We need to have a CD to redeploy the new version of the service, but we want to prevent K8s from killing our service if there is an open GRPC stream.

**The question**
Do we have a support for graceful shutdown of the service only when we don't have open connections?
I see this: https://github.com/grpc-ecosystem/grpc-spring/blob/master/grpc-server-spring-boot-starter/src/main/java/net/devh/boot/grpc/server/serverfactory/GrpcServerLifecycle.java#L58
But I don't see we check the state of the service itself

**Comment by ST-DDT** [comment]
Have you tried this config:

https://github.com/grpc-ecosystem/grpc-spring/blob/e52df51897a4f5bebbe0e82d5fefe3d419d86c08/grpc-server-spring-boot-starter/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java#L111

**Comment by o-shevchenko** [comment]
Thanks
I haven't tried it yet. I will test it with K8s and let you know the result

**Comment by o-shevchenko** [comment]
Looks like it works. At least I see that service waits for 5 minutes before shutdown. But I configured `shutdownGracePeriod=-1`
For K8s you should additionally adjust `terminationGracePeriodSeconds` for 24h (just for testing).
I tried to configure:
```
grpc:
  server:
    port: 6565
    reflection-service-enabled: true
    shutdown-grace-period: -1
    enable-keep-alive: true
    keep-alive-time: 86400
    keep-alive-timeout: 86400
    permit-keep-alive-without-calls: true
    permit-keep-alive-time: 86400
 ```
 But service is getting killed after 5 minutes, I can't find what else we can configure and what is that 5 minutes timeout.
 ```
GrpcServerLifecycle          : Completed gRPC server shutdown
```

**Comment by o-shevchenko** [comment]
Looks like it works. At least now I see that K8s can't kill it for configured period of time. 
Additionaly to `shutdownGracePeriod =-1` I configured `terminationGracePeriodSeconds` for 24h (just for testing).
I also tried to adjust various confs:
```
grpc:
  server:
    port: 6565
    reflection-service-enabled: true
    shutdown-grace-period: -1
    enable-keep-alive: true
    keep-alive-time: 86400
    keep-alive-timeout: 86400
    permit-keep-alive-without-calls: true
    permit-keep-alive-time: 86400
 ```

But after 5 minutes the app is getting killed anyway. I can't find a conf that is responsible for that.
```
[SpringApplicationShutdownHook] [trace_id=, span_id=]n.d.b.g.s.s.GrpcServerLifecycle          : Completed gRPC server shutdown
```
